# Minecraft & Forge Versionen (Zentral für alle Mods)
mc_version=1.20.1
forge_version=47.2.0
mappings_channel=official
mappings_version=1.20.1

# Globale Mod-Infos
mod_authors=KarlKarlmann

# ==========================================
# VERSIONEN DER MODS
# ==========================================
version_stones-core=1.1.1
version_stones-visuals=1.1.1
version_stones-editor=1.1.1

# ==========================================
# GROUPS (JAVA PACKAGES) DER MODS
# ==========================================
group_stones-core=net.stones
group_stones-visuals=net.stones.visuals
group_stones-editor=net.stones.editor